spring:
  cloud:
    gateway:
      routes:

        - id: product_route
          uri: lb://folimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://folimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://folimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://folimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: folimall_host_route
          uri: lb://folimall-product
          predicates:
            - Host=folimall.com,item.folimall.com

        - id: folimall_search_route
          uri: lb://folimall-search
          predicates:
            - Host=search.folimall.com

        - id: folimall_auth_route
          uri: lb://folimall-auth-server
          predicates:
            - Host=auth.folimall.com

        - id: folimall_cart_route
          uri: lb://folimall-cart
          predicates:
            - Host=cart.folimall.com

        - id: folimall_order_route
          uri: lb://folimall-order
          predicates:
            - Host=order.folimall.com
